### ISSUE TITLE
Project?

### ISSUE THREAD

**Issue by stevetoro** [YukaProg/jammming#1]
Where are all your actual Jammming-related files and folders?

You should upload everything generated by `create-react-app`, except for the `node_modules` folder (which is ignored by default if you don't delete the generated `.gitignore` file).

**Comment by YukaProg** [comment]
Thank you so much for your review! I thought I have uploaded everything but I might have followed wrong steps... I have uploaded my project to master branch this time. I would appreciate if you could check again if this works. ps: I'm sorry for taking time to response as I'm working from Japan.
